version: "3.8"
services:
  wallet-service:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    depends_on:
      - wallet-database
      - wallet-redis
    command: sh -c /app/migrations/scripts/migrations.sh

  wallet-database:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: Qwerty1234
      POSTGRES_DB: wallet-service
    volumes:
      - ./pg_data:/var/lib/postgresql/data
    ports:
      - 5432:5432

  wallet-redis:
    image: redis:latest
    container_name: wallet_redis
    ports:
      - "6379:6379"
    volumes:
      - ./redis_data:/data